navmenu:
- title: Home
  href: /
- title: Syllabus
  href: /syllabus/
- title: Lectures
  href: /lectures/
- title: Assignments
  href: /assignments/
- title: Tester
  href: https://cs531.cs.odu.edu/
- title: Discussions
  href: https://github.com/cs531-f19/discussions
permalink: pretty
defaults:
- scope:
    path: ""
  values:
    layout: "default"
- scope:
    path: "assignments/*"
  values:
    layout: "assignment"
